#!/bin/bash
################################################################################
# OpenERP-inator, a tool to manage OpenERP server instances
# Author: Daniel Reis, 2013
#
################################################################################

#fixed parameters:
OEADMIN_VERSION="0.3b"
OEADMIN_USER="`whoami`"
OEADMIN_HOME="/opt/openerp"
OEVERSION="7.0"
color='\e[1;34m'
endColor='\e[0m'

# Basic usage instruction
if [ -z "$1" ]; then
    echo "usage: oetor <command> [<args>]

The most commonly used commands are:
  help              Show all commands and detailed usage instructions.
  get-dependencies  Install PostgreSQL and OpenERP system dependencies.
  init              Initialize a OpenERP home and it's server sources.
  create            Create an OpenERP server instance.
  start             Start running a server instance.
  test              Create a temporay db and run tests for an instance

Type \`oetor help\` to show all commands available.
Type \`oetor <command>\` (with no argument) to get more help on a command.
"
    exit 0
fi

#OPTION=$1
case "$1" in


help)
  echo "usage: oetor <command> [<args>]
OpenERP-inator, a tool to manage and test multiple OpenERP server instances.
https://github.com/dreispt/oetor

<fluff> Dominate the entire ERP tri-state area by easilly installing and 
creating an army of OpenERP server instances in your server. Beware of the 
self-destruct button. </fluff>

For an easy and  quick start run: ./oetor auto-install
This will make an automatic full installation, including the creation of an
initial "demo" OpenERP instance. It's equivalent to running the sequence of
commands: get-dependencies; init; get-source; create demo.

Commands available:

  version           Display script's version info.
  get-dependencies  Install system dependencies including the PostgreSQL
                    database. Requires sudoer privilege.
  init [VERSION]    Creates db role for current user and the directory
                    structure. Requires sudoer privilege. VERSION is the
                    OpenERP version: 7.0 | trunk | 6.1.
  get-latest        Retrieves source code from nightly builds repository, into
                    the 'shared' directory.
  get-source        Retrieves source code from Lanchpad repositories, into
                    the 'shared' directory.
  update-source     Updates the sources with most recent versions.
  version-source    Displays the sources revision numbers.
  create NAME [PORT] [FIXED_OPTIONS]
                    Create an OpenERP 7 database and instance named "NAME" and
                    listening at port "PORT". If additional "FIXED_OPTIONS" are
                    provided, they will be included in the generated 'start'
                    script.
  start OEVERS NAME Starts this server instance.
  test OEVERS NAME  Creates a test database and runs tests for the instance.
  fake-smtp         Launch a test SMTP server on localhost, printing to stdout.

An OpenERP instance is a directory inside oetor's home directory. It can be
started running the `start` script and and includes a `openerp-server.conf`
configuration file used by the instance.

If the `start` script is provided with additional parameters, these will be
passed to the openerp-server.
For example: ./start.sh -u all --stop-after-init

The contained directories are automatically added to the addons_path upon server
start. By default includes symlinks to the official addons sources in the
'shared' directory.
"
    ;;


version)
    echo "oetor version: $OEADMIN_VERSION"
    echo "oetor home: $OEADMIN_HOME"
    ;;


get-dependencies)
    #--------------------------------------------------
    # Install Postgres and System dependencies
    #  - tested with Ubuntu 12
    #--------------------------------------------------
    echo -e "\n---- Installing PostgreSQL ----"
    sudo apt-get install postgresql

    echo -e "\n---- Installing system packages ----"
    yes | sudo apt-get install bzr bzrtools python-pip git

    echo -e "\n---- Installing python packages ----"
    yes | sudo apt-get install python-dateutil python-docutils python-feedparser \
    python-gdata python-jinja2 python-ldap python-libxslt1 python-lxml python-mako \
    python-mock python-openid python-psycopg2 python-psutil python-pybabel \
    python-pychart python-pydot python-pyparsing python-reportlab python-simplejson \
    python-tz python-unittest2 python-vatnumber python-vobject python-webdav \
    python-werkzeug python-xlwt python-yaml python-zsi python-gdata

    #echo -e "\n---- Install python libraries ----"
    #sudo pip install gdata
    echo -e "Dependencies installed."
    ;;


init)
    #--------------------------------------------------
    # Setup directories
    #  - repo stored in $OEADMIN_HOME (/opt/openerp)
    #  - reexecution safe (nothing is done)
    #  - repo is a git clone: `git pull` will get it's latest version
    #--------------------------------------------------

    if [ ! -d /var/log$OEADMIN_HOME ] ; then
        echo -e "* Creating base log directory /var/log$OEADMIN_HOME ..."
        sudo mkdir -p /var/log$OEADMIN_HOME
        sudo chown $OEADMIN_USER:root /var/log$OEADMIN_HOME
    fi

    if [ ! -d $OEADMIN_HOME ] ; then
        echo -e "* Creating oetor home directory $OEADMIN_HOME ..."
        sudo mkdir -p $OEADMIN_HOME/shared
        sudo chown -R $OEADMIN_USER:root $OEADMIN_HOME
        sudo git clone https://github.com/dreispt/oetor $OEADMIN_HOME/shared/oetor
        ln -s $OEADMIN_HOME/shared/oetor/oetor $OEADMIN_HOME/oetor
    else
        echo -e "* Getting oetor latest version on directory $OEADMIN_HOME/shared/oetor ..."
        git --git-dir=$OEADMIN_HOME/shared/oetor pull
    fi
    ;;


install)
    if [ -z "$3" ] ; then
        echo "Usage: oetor install ORIGIN VERSION"
        exit 0
    fi

    ORIGIN="$2"
    OEVERSION="$3"

    case $ORIGIN in
    
        latest)
            echo "Retrieving nightly build sources to $OEADMIN_HOME/shared/latest-$OEVERSION:"
            echo -e "${color}* Downloading $OEVERSION nightly build ...${endColor}"
            mkdir -p $OEADMIN_HOME/shared
            wget --no-clobber http://nightly.openerp.com/$OEVERSION/nightly/src/openerp-$OEVERSION-latest.tar.gz -P $OEADMIN_HOME/shared

            echo -e "${color}* Uncompressing files ...${endColor}"
            rm -rf $OEADMIN_HOME/shared/~tmp
            mkdir -p $OEADMIN_HOME/shared/~tmp
            tar xf $OEADMIN_HOME/shared/openerp-$OEVERSION-latest.tar.gz --directory=$OEADMIN_HOME/shared/~tmp

            echo -e "${color}* Installing shared source files ...${endColor}"
            rm -rf $OEADMIN_HOME/shared/latest-$OEVERSION/*
            mkdir -p $OEADMIN_HOME/shared/latest-$OEVERSION
            mv $OEADMIN_HOME/shared/~tmp/`ls $OEADMIN_HOME/shared/~tmp/`/* $OEADMIN_HOME/shared/latest-$OEVERSION/
            ;;
            
        source)
            OEADMIN_DIR="$OEADMIN_HOME/shared/$ORIGIN-$OEVERSION"
            mkdir -p $OEADMIN_DIR
            if [ ! -d $OEADMIN_DIR/addons ] ; then
                echo -e "\n${color}Checkout of openerp-addons/$OEVERSION ...${endColor}"
                rm -rf $OEADMIN_DIR/~tmp
                bzr checkout --lightweight https://launchpad.net/~openerp/openobject-addons/$OEVERSION $OEADMIN_DIR/~tmp
                mv $OEADMIN_DIR/~tmp $OEADMIN_DIR/addons
            fi
            if [ ! -d $OEADMIN_DIR/web ] ; then
                echo -e "\n${color}Checkout of openerp-web/$OEVERSION ...${endColor}"
                rm -rf $OEADMIN_DIR/~tmp
                bzr checkout --lightweight https://launchpad.net/~openerp/openerp-web/$OEVERSION $OEADMIN_DIR/~tmp
                mv $OEADMIN_DIR/~tmp $OEADMIN_DIR/web
            fi
            if [ ! -d $OEADMIN_DIR/server ] ; then
                echo -e "\n${color}Checkout of openerp-server/$OEVERSION ...${endColor}"
                rm -rf $OEADMIN_DIR/~tmp
                bzr checkout --lightweight https://launchpad.net/~openerp/openobject-server/$OEVERSION $OEADMIN_DIR/~tmp
                mv $OEADMIN_DIR/~tmp $OEADMIN_DIR/server
            fi
            echo -e "\nLaunchpad sources ready."
            ;;
        
        *)
            OEADMIN_DIR="$OEADMIN_HOME/shared/$ORIGIN"
            if [ ! -d "$OEADMIN_DIR" ] ; then
                echo -e "\n${color}Checkout of $OEVERSION to $ORIGIN ...${endColor}"
                rm -rf $OEADMIN_HOME/shared/~tmp
                bzr checkout --lightweight $OEVERSION $OEADMIN_HOME/shared/~tmp
                mv $OEADMIN_HOME/shared/~tmp $OEADMIN_DIR
            fi
            echo -e "\nLaunchpad sources ready."
            ;;
        
    esac
    

update)
    #TODO review this
    #--------------------------------------------------
    # Update the sources downloaded with "get-source"
    #--------------------------------------------------
    if [ -z "$3" ] ; then
        echo "Usage: oetor update <SOURCE> [VERSION]"
        exit 0
    fi
            
    OESOURCE_DIR="$2"

    OEADMIN_DIR=$OEADMIN_HOME/shared/$OESOURCE_DIR
    echo -e "Updating openerp-addons"
    bzr update $OEADMIN_DIR/addons
    echo -e "* Updating openerp-web"
    bzr update $OEADMIN_DIR/web
    echo -e "* Updating openerp-server"
    bzr update $OEADMIN_DIR/server
    echo "Sources updated."
    ;;


version-source)
    #TODO review this
    #-------------------------------------------------
    # List version revision numbers for sources downloaded with "get-source"
    #--------------------------------------------------
    if [ "$2" ] ; then
        OESOURCE_DIR="$2"
    else
        echo "Usage:
oetor version-source <source-dirname>"
        exit 0
    fi

    OEADMIN_DIR=$OEADMIN_HOME/shared/$OESOURCE_DIR
    echo -e "* Shared sources revision numbers for $OESOURCE_DIR:"
    echo -en "server\t"
    bzr revno -q $OEADMIN_DIR/server
    echo -en "addons\t"
    bzr revno -q $OEADMIN_DIR/addons
    echo -en "web\t"
    bzr revno -q $OEADMIN_DIR/web
    ;;


fake-smtp)
    sudo python -m smtpd -n -c DebuggingServer localhost:25
    ;;


create-branch)
    #--------------------------------------------------
    # Create a new server Instance and setup a Branch
    # It's meant to be used through `create` and `branch`, but can also be used directly
    #--------------------------------------------------

    # Check minimun parameters supplied
    if [ -z "$4" ] ; then
#oetor create-branch <INSTANCE> <BASE> <MPURL> <BRANCHNAME> [PORT] [FIXED_PARAMS]
#oetor create-branch <INSTANCE> <BASE> --no-branch [PORT] [FIXED_PARAMS]"
#
        echo "Usage:
oetor create-branch <INSTANCE> <BRANCHNAME> <MPURL> <BASEDIR> [PORT] [FIXED_PARAMS]
oetor create-branch <INSTANCE> --no-branch <BASEDIR> [PORT] [FIXED_PARAMS]"
        exit 0
    fi

    # Get version and instance name
    INSTANCE="$2"

    # Get optional branch    
    if [ "$3" = "--no-branch" ] ; then
        BRANCHNAME=""
        MPURL=""
        shift 1
    else
        BRANCHNAME="$3"
        MPURL="$4"
        shift 2
    fi

    # Base directory
    OEBASE="$3"
    if [ "$3" = "--no-base" ] ; then
        OEBASE=""
    fi
    if [ ! -d "$OEADMIN_HOME/shared/$OEBASE" ] ; then
        echo "STOPPING: HOME/shared/$OEBASE does not exist."
        exit 0
    fi

    # Get optional port number    
    if [ -z "$4" ] ; then
        PORT=8069
    else
        PORT="$4"
        shift 1
    fi
    
    #--------------------------------------------------
    # - create instance
    #--------------------------------------------------

    # Create psql role if missing
    if [ -z `psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$OEADMIN_USER'"` ] ; then
        echo -e "* Creating database role $OEADMIN_USER ..."
        sudo su -c "createuser --createdb --no-createrole --no-superuser $OEADMIN_USER" postgres
    fi

    OEADMIN_DIR="$OEADMIN_HOME/$INSTANCE"
    
    # Create instance directory
    if [ ! -d "$OEADMIN_DIR/common" ] ; then
        echo "* Creating instance directory ..."
        mkdir -p "$OEADMIN_DIR/common"
    fi

    # Create symlink to server source
    if [ ! -z "$OEBASE" ] ; then
        if [ ! -d "$OEADMIN_DIR/base" ] ; then
            echo "* Linking to server ..."
            ln -s "$OEADMIN_HOME/shared/$OEBASE" "$OEADMIN_DIR/base"
        fi
    fi

    #create database
    if [ ! `psql $INSTANCE -c "select 1"` == 0 ] ; then
        echo "* Creating instance database $INSTANCE ..."
        createdb "$INSTANCE"
    fi

    #--------------------------------------------------
    # - create config
    #--------------------------------------------------

    if [ ! -f "$OEADMIN_DIR/openerp-server.conf" ] ; then
        echo "* Creating instance config file ..."
        # TODO: better conf file (?)
        echo "[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_user = $OEADMIN_USER
db_name = $INSTANCE
netrpc = False
xmlrpcs = False
log_handler = ['werkzeug:CRITICAL']
" > $OEADMIN_DIR/openerp-server.conf
    fi
    
    shift 3
    
    if [ ! -f "$OEADMIN_DIR/norm-base" ] ; then
        echo "$OEADMIN_HOME/oetor $INSTANCE --no-branch $PORT $*" > "$OEADMIN_DIR/norm-base"
        chmod ug+x "$OEADMIN_DIR/norm-base"
    fi

    #--------------------------------------------------
    # - DONE with instance
    #--------------------------------------------------
    echo "
Instance \"$INSTANCE\" created configured for port $PORT.
To start it type: $OEADMIN_DIR/norm-base start
To use it browse: http://`hostname`:$PORT
"

    #--------------------------------------------------
    # - create branch
    #--------------------------------------------------
    if [ ! -z "$MPURL"] ; then

        # Get MP sources
        if [ ! -d "$OEADMIN_DIR/$BRANCH_NAME" ] ; then
            echo "* Retrieving branch ..."
            bzr branch "$MPURL" "$OEADMIN_DIR/$BRANCH_NAME"
        fi
        
        # create non existing database    
        if [ ! `psql $BRANCH_NAME-$INSTANCE -c "select 1"` == 0 ] ; then
            echo "* Creating database $BRANCH_NAME-$INSTANCE ..."
            createdb "$BRANCH_NAME-$INSTANCE"
        fi

        # create norm script
        if [ ! -f "$OEADMIN_DIR/norm-$BRANCH_NAME" ] ; then
            # TODO: IMPORTANT - need to pass BRANCH_NAME to oetor!
            echo "$OEADMIN_HOME/oetor $INSTANCE $BRANCH_NAME $PORT $*" > $OEADMIN_DIR/norm-$BRANCH_NAME
            chmod ug+x "$OEADMIN_DIR/$INSTANCE/norm-$BRANCH_NAME"
        fi

        #--------------------------------------------------
        # - DONE with branch
        #--------------------------------------------------
        echo "
Branch $BRANCH_NAME ready.
To control it:    $OEADMIN_DIR/norm-$BRANCH_NAME
"
    fi
    
    ;;


create)
    #--------------------------------------------------
    # Create a new instance:
    #   oetor create INSTANCE <BASE> [PORT] [FIXED_PARAMS]
    #--------------------------------------------------

    # Check OpenERP version parameter
    if [ -z "$3" ] ; then
        echo "Usage:   oetor create INSTANCE BASEDIR"
        echo "Example: oetor create myserver latest-7.0"
        exit 0
    else
        # Get parameters
        INSTANCE="$2"
        OEBASE="$3"
        shift 3
        $0 branch $OEVERSION $INSTANCE --no-branch $OEBASE $*
    fi
    ;;
    
    
branch)
    #--------------------------------------------------
    # Create a new brench inside an instance:
    #   oetor branch INSTANCE <BRANCHNAME> <MPURL> [PORT] [FIXED_PARAMS]
    #--------------------------------------------------

    # Check OpenERP version parameter
    if [ -z "$4" ] ; then
        echo "Usage:   oetor branch INSTANCE BRANCHNAME BRANCHURL [PORT] [FIXED_PARAMS]"
        echo "Example: oetor branch myserver7 myproject lp:myproject/7.0"
        exit 0
    else
        # Get parameters
        INSTANCE="$2"
        BRANCHNAME="$3"
        BRANCHURL="$4"
        shift 4
        $0 create-branch $INSTANCE $BRANCHNAME $BRANCHURL --no-base $*
    fi
    ;;
    
    
branch-install)
    #--------------------------------------------------
    if [ -z "$4" ] ; then
        echo "usage: oetor branch-install INSTANCE BRANCHNAME BRANCHURL [PORT] [FIXED_PARAMS]"
        echo "Retrieve a branch from Launchpad and install all its modules."
        exit 0
    fi
    #--------------------------------------------------
 
    # Get parameters
    INSTANCE="$2"
    BRANCHNAME="$3"
    BRANCHURL="$4"
    
    # branch
    shift 1
    $0 branch $*
    
    echo -e "Branch contents:"
    ls "$OEADMIN_HOME/$INSTANCE/$BRANCHNAME"
    
    # Init modules
    echo -e "\nInstalling branch modules ..."
    MODULES="`ls -d1 $OEADMIN_HOME/$INSTANCE/$BRANCHNAME/*/ | xargs -I file basename file | tr '\n' ','`"
    echo "Modules to install: ${MODULES%?}" # remove trailing comma
    $0 start $INSTANCE $BRANCHNAME --init="${MODULES%?}" --stop-after-init
    ;;    


start)
    #--------------------------------------------------
    if [ -z "$3" ] ; then
        echo "usage: oetor start INSTANCE BRANCHNAME [PORT] [PARAMS]"
        echo "Start an OpenERp server."
        exit 0
    fi
    #--------------------------------------------------
 
    # Get parameters
    INSTANCE="$2"
    BRANCH_NAME="$3"
    
    # Get optional port number    
    if [ -z "$4" ] ; then
        PORT=8069
    else
        PORT="$4"
        shift 1
    fi
    
    shift 3
    ADDONS="`ls -dm $OEADMIN_HOME/$INSTANCE/common/*/|tr -d '[:space:]'`"
    $OEADMIN_HOME/$INSTANCE/base/server/openerp-server --xmlrpc-port=$PORT -d $BRANCH_NAME-$INSTANCE $* --addons-path="$OEADMIN_HOME/$INSTANCE/$BRANCH_NAME,$ADDONS" --config="$OEADMIN_HOME/$INSTANCE/openerp-server.conf" $*
        ;;


test)
    OEVERSION=$2
    INSTANCE=$3
    dropdb $INSTANCE-TEST-$OEVERSION
    createdb $INSTANCE-TEST-$OEVERSION
    shift 3
    $OEADMIN_HOME/$OEVERSION/$INSTANCE/start --test-enable --stop-after-init $*
    ;;


remove)
    echo "Sorry, the self-destruct button is currently disabled. To go ahead run:
rm -r $OEADMIN_HOME/VERSION/INSTANCE
dropdb INSTANCE-VERSION"
    ;;


auto-install)
    $0 get-dependencies
    $0 init
    $0 install source 7.0
    $0 create demo source-7.0
    ;;

esac
